sudo: required
services:
  - docker

before_install:
  - docker build -t extramagnetdavid/fib-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true extramagnetdavid/fib-client-test npm test -- --coverage

after_success:
  - docker build -t extramagnetdavid/fib-nginx ./nginx
  - docker build -t extramagnetdavid/fib-client ./client
  - docker build -t extramagnetdavid/fib-api ./server
  - docker build -t extramagnetdavid/fib-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push extramagnetdavid/fib-nginx
  - docker push extramagnetdavid/fib-client
  - docker push extramagnetdavid/fib-api
  - docker push extramagnetdavid/fib-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'fib-complex'
  env: 'Fibcomplex-env'
  bucket_name: 'elasticbeanstalk-us-east-2-264856337147'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY